### ISSUE TITLE
Not in HACS

### ISSUE THREAD

**Issue by Joeri94** [gcorgnet/sensor.emby_upcoming_media#10]
Hello,

I was looking for your plugin but cant find it anymore in the HACS store.
Do you know why its gone?

**Comment by gcorgnet** [comment]
I'm pretty sure it's still there, according to the list here: https://hacs.xyz/docs/default_repositories

**Comment by Joeri94** [comment]
I'm very very sorry, 
I was busy with the upcoming card mod and the emby upcoming card sensor.
This issue was for the upcoming card mod.

Excuse me

**Comment by gcorgnet** [comment]
all good :-)
