### ISSUE TITLE
Version key in manifest file

### ISSUE THREAD

**Issue by LEJOUI** [gcorgnet/sensor.emby_upcoming_media#16]
Updating to the latest beta of HA gives the following warning.

`No 'version' key in the manifest file for custom integration 'emby_upcoming_media'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'emby_upcoming_media'`

More information: https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

edit: changed link
## Configuration

```yaml

Add your logs here.

```

## Debug log

```text

Add your logs here.

```

**Comment by snipes040** [comment]
+1 to this!

**Comment by gcorgnet** [comment]
Fixed.
