### ISSUE TITLE
Component does not load in Home Assistant Core-2021.6

### ISSUE THREAD

**Issue by darkenbula** [gcorgnet/sensor.emby_upcoming_media#19]
The custom integration 'emby_upcoming_media' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by shaft8472** [comment]
You can temporarily solve this by editing /config/custom_components/emby_upcoming_media/manifest.json and add:
`"version": "0.3.4",`

**Comment by gcorgnet** [comment]
Fixed,
