### ISSUE TITLE
Make this card installable via HACS

### ISSUE THREAD

**Issue by Tuumke** [gcorgnet/sensor.emby_upcoming_media#2]
**Is your feature request related to a problem? Please describe.**
Maybe, i wouldnt report this as a problem just jet. Most cards like Sonarr and Radarr are able to be installed using HACS. This card for Emby isnt?

**Describe the solution you'd like**
Install the card via HACS like the Sonarr / Radarr cards

**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable

**Comment by soloam** [comment]
Plus one to this

**Comment by geekaroni** [comment]
I spent two hours trying to get this working. Meanwhile sonarr and radarr work fine. When I add the details to config, ha won’t even restart. Something isn’t right. People on the forum having the same issue.

**Comment by skank01** [comment]
+1

**Comment by gcorgnet** [comment]
I have mine installed through HACS.
What I had to do was add my repo as a Custom Repository (under HACS/Settings)
Add `https://github.com/gcorgnet/sensor.emby_upcoming_media` as an Integration.
Let me nkow if it helps

**Comment by gcorgnet** [comment]
I've also submitted a [PR](https://github.com/hacs/default/pull/390) to include this in HACS.... 🤞

**Comment by skank01** [comment]
Cool thx !

**Comment by skank01** [comment]
Nevermind my userid question, found it using emby api browser

Op za 2 mei 2020 om 01:18 schreef Guillaume Corgnet <
notifications@github.com>:

**Comment by gcorgnet** [comment]
This component is now available through HACS
