### ISSUE TITLE
Emby User ID

### ISSUE THREAD

**Issue by darkenbula** [gcorgnet/sensor.emby_upcoming_media#3]
How do we find the user id?  It's unclear how we 'spy on the emby api calls'

**Comment by gcorgnet** [comment]
Hi, what I mean by that, is browse to embi and using the Developer Tools, have a look at the calls being made. This will give you the user id for y our user (it's a random string)

eg: see below

![image](https://user-images.githubusercontent.com/4731735/71695143-197cf800-2e16-11ea-8f12-95ba9bdb968b.png)

**Comment by dennyreiter** [comment]
I was also able to find mine from the admin dashboard by going to Users, then selecting the user to edit and copying it from the address bar:

/web/index.html#!/useredit.html?userId=84ff7f73b1af45b4834b9fc857170fa1
