### ISSUE TITLE
Request recently added movies (ls tvshows but seperate)

### ISSUE THREAD

**Issue by skank01** [gcorgnet/sensor.emby_upcoming_media#6]
Hi,

Would love to see recently added movies (next to upcoming media).
This would rock with the lovelace upcoming media card for home assistant
Even recently added tvshows...
(the kodi plugin has it, but is not an option for me, cause i'm using emby)
Hope you're willing to support.

Thx!

**Comment by gcorgnet** [comment]
Hey mate, if I understand what you want correctly, then this is exactly what this does. It shows the list of the last 5 movies.
Did you give it a try?

**Comment by skank01** [comment]
Oh :) not yet :)
Thx for letting me know

I thought it showed upcoming new movies (that arent even in the library)
it's a misunderstanding then ;)
Gonna try asap this weekend, thx for creating this

**Comment by gcorgnet** [comment]
Note: you can also get your TV shows to show up. (take a look at the sample config in the [ReadMe](https://github.com/gcorgnet/sensor.emby_upcoming_media/blob/master/README.md)

**Comment by skank01** [comment]
@gcorgnet I'm not sure if i need this one or the one for kodi

I'm using emby for kodi.. 
I installed the default emby component, and i see the emby mediaplayers like chromebrowser and stuff, but not the ones i really need (my kodi machines)
Thats making me think i need the kodi one?
or am i wrong?
even for the database, cause emby in fact does my database... not sure kodi or this one?
