### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by skank01** [gcorgnet/sensor.emby_upcoming_media#7]
Is it possible to add pulling info:
- genres
- studio
- day of realse

Or is this info not available inside emby?

Now i only have on the cards:
- title
- rating
- runtime

**Comment by gcorgnet** [comment]
I'll take a look.

**Comment by skank01** [comment]
Thanks mate

**Comment by skank01** [comment]
Also for tvshows seasons and episode title

Perhaps look at the possible text content options:
https://github.com/custom-cards/upcoming-media-card

**Comment by gcorgnet** [comment]
This has been added and is now available
