### ISSUE TITLE
Please clarify instructions to get the user id

### ISSUE THREAD

**Issue by titomontes** [gcorgnet/sensor.emby_upcoming_media#9]
**Is your feature request related to a problem? Please describe.**
User Id is cryptic for the noob, which I´m not. There´s no explanation in the general instructions to what is the user Id

**Describe the solution you'd like**
Please modify the instructions as to show the two methods to find it (through thw browser´s details and in the adrress bar)

**Comment by gcorgnet** [comment]
There is now detailed instructions in the README
